services:
  postgres:
    image: 'postgres:latest'
    container_name: "contractor_postgres"
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contractor_db
    restart: always

volumes:
  db_data: